/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

import "sst"
declare module "sst" {
  export interface Resource {
    "Env": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}

import "sst"
export {}